Cloud name: dsib9klin

API key: 144329726239136

API secret: Jofmyviar6Q4p7UCGDvYmTWKIYU

API environment variable: CLOUDINARY_URL=cloudinary://144329726239136:Jofmyviar6Q4p7UCGDvYmTWKIYU@dsib9klin



